### ISSUE TITLE
Create a Github Action

### ISSUE THREAD

**Issue by TheBookKnight** [TheBookKnight/npm-gitver#5]
Create a Github Action with several optional inputs for `branch` or `filePath`

```yaml
- name: Generate version
  uses: joshua/npm-gitver-action@v1
  id: gitver
  with:
    file: './package.json'
    branch: true

- name: Show version
  run: echo "Version is ${{ steps.gitver.outputs.version }}"
```
